name: Deploy Helm Chart to GKE

on:
  push:
    paths:
      - 'charts/my-app/**'
    branches:
      - aaa-001

env:
  GCP_PROJECT_ID: your-gcp-project-id
  GKE_CLUSTER_NAME: your-cluster-name
  GKE_CLUSTER_REGION: your-cluster-region
  HELM_RELEASE_NAME: my-app
  HELM_CHART_PATH: ./charts/my-app
  KUBERNETES_NAMESPACE: default

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      - name: Set up kubectl
        uses: google-github-actions/setup-gcloud@v1

      - name: Authenticate kubectl to GKE
        run: |
          gcloud container clusters get-credentials "$GKE_CLUSTER_NAME" \
            --region "$GKE_CLUSTER_REGION" \
            --project "$GCP_PROJECT_ID"

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Deploy with Helm
        run: |
          helm upgrade --install "$HELM_RELEASE_NAME" "$HELM_CHART_PATH" \
            --namespace "$KUBERNETES_NAMESPACE" \
            --create-namespace \
            --wait
