name: Sample Workflow 1

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      name:
        description: 'Your name'
        required: true
      environment:
        description: 'Target environment'
        required: true

jobs:
  print-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello, ${{ github.event.inputs.name }}"
          echo "Environment: ${{ github.event.inputs.environment }}"
